Feature/peer review stage
nationalarchives/tna-profile-page pull request #1
Opened 2017-06-27 09:18 UTC by netdesignr

Hi @punalsc,

Can you please review this PR?

Thank you so much !!!!

2017-06-27 17:03 UTC, punalsc requested changes
Can you please have a look at the comments and fix accordingly.

2017-06-27 17:03 UTC, punalsc commented on css/profile-page-no-sidebar.css
> +      width: 100% !important; } }
Can you find a way to not use, !important.

Maybe try using css specificity.

2017-06-27 17:03 UTC, punalsc commented on inc/functions/content/profile-details-page-content.php
> +                        <?= profile_feature_image('/../../img/profile-fall-back.jpg', has_post_thumbnail()); ?>
Try and be consistent with using the php echo shortcut. It has been used in some places and not others.

2017-06-27 17:03 UTC, punalsc commented on inc/functions/content/profile-landing-page-content.php
> +                            <p>Position: <?= ${$position} ?></p>
Again, try and be consistent using the php shortcut.

2017-06-27 17:03 UTC, punalsc commented on inc/functions/content/profile-details-page-content.php
> +                    <?php echo ${$post_meta_body} ?>
Try and be consistent using the shortcut method
`<?= ${$post_meta_body} ?>`

2017-06-27 17:03 UTC, punalsc commented on inc/post-type-meta-box/profile-details-page-meta-box.php
> +        echo '<tr>',
Nothing wrong with the code, but i like to suggest using
`sprintf()`

Just to make it a little bit more readable.

2017-06-28 14:44 UTC, netdesignr commented on css/profile-page-no-sidebar.css
> +      width: 100% !important; } }
I've added a class to the body and now everything it is namespaced properly.

2017-06-28 14:47 UTC, netdesignr commented on inc/functions/content/profile-details-page-content.php
> +                        <?= profile_feature_image('/../../img/profile-fall-back.jpg', has_post_thumbnail()); ?>
I've only introduced the = later in the dev and I've missed some during refactoring

2017-06-28 14:47 UTC, netdesignr commented on inc/functions/content/profile-details-page-content.php
> +                        <?= profile_feature_image('/../../img/profile-fall-back.jpg', has_post_thumbnail()); ?>
So it's done

2017-06-28 14:47 UTC, netdesignr commented on inc/functions/content/profile-details-page-content.php
> +                    <?php echo ${$post_meta_body} ?>
Done

2017-06-28 14:48 UTC, netdesignr commented on inc/functions/content/profile-landing-page-content.php
> +                            <p>Position: <?= ${$position} ?></p>
Done

2017-06-28 14:48 UTC, punalsc commented on css/profile-page-no-sidebar.css
> +      width: 100% !important; } }
Great

2017-06-28 14:48 UTC, punalsc commented on inc/functions/content/profile-details-page-content.php
> +                        <?= profile_feature_image('/../../img/profile-fall-back.jpg', has_post_thumbnail()); ?>
ok great

2017-06-28 14:48 UTC, netdesignr commented on inc/post-type-meta-box/profile-details-page-meta-box.php
> +        echo '<tr>',
I'm afraid this will require too much work just to eventually do the same thing. However, this is good to keep in mind whenever got loads of concats.

2017-06-28 15:20 UTC, punalsc commented on inc/post-type-meta-box/profile-details-page-meta-box.php
> +        echo '<tr>',
Ok great.

2017-06-29 14:47 UTC, punalsc approved these changes
Everything looks great.

2017-06-29 14:48 UTC, merged